{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clustassess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ClustAssess_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ClustAssess/ClustAssess_{{ version }}.tar.gz
  sha256: 33d123a18f4212726bca09b68990e14e27520add3e9086cf3f393b68c655fb67

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-doparallel
    - r-dplyr
    - r-dt
    - r-fastcluster
    - r-foreach
    - r-ggnewscale
    - r-ggplot2
    - r-ggrastr
    - r-ggrepel
    - r-ggtext
    - r-gmedian
    - r-gprofiler2
    - r-igraph
    - r-irlba
    - r-jsonlite
    - r-leiden
    - r-magrittr
    - r-matrix
    - r-matrixstats
    - r-paletteer
    - r-plotly
    - r-progress
    - r-qualpalr
    - r-rann
    - r-rcpp
    - r-reshape2
    - r-rlang
    - r-seurat
    - r-shiny
    - r-shinyjs
    - r-shinylp
    - r-shinywidgets
    - r-stringr
    - r-uwot
  run:
    - r-base
    - r-doparallel
    - r-dplyr
    - r-dt
    - r-fastcluster
    - r-foreach
    - r-ggnewscale
    - r-ggplot2
    - r-ggrastr
    - r-ggrepel
    - r-ggtext
    - r-gmedian
    - r-gprofiler2
    - r-igraph
    - r-irlba
    - r-jsonlite
    - r-leiden
    - r-magrittr
    - r-matrix
    - r-matrixstats
    - r-paletteer
    - r-plotly
    - r-progress
    - r-qualpalr
    - r-rann
    - r-rcpp
    - r-reshape2
    - r-rlang
    - r-seurat
    - r-shiny
    - r-shinyjs
    - r-shinylp
    - r-shinywidgets
    - r-stringr
    - r-uwot

test:
  commands:
    - $R -e "library('ClustAssess')"           # [not win]
    - "\"%R%\" -e \"library('ClustAssess')\""  # [win]

about:
  home: https://github.com/Core-Bioinformatics/ClustAssess
  license: MIT
  summary: A set of tools for evaluating clustering robustness using proportion of ambiguously clustered pairs (Senbabaoglu et al. (2014) <doi:10.1038/srep06207>), as well as similarity across methods and method stability using element-centric clustering comparison (Gates et al. (2019) <doi:10.1038/s41598-019-44892-y>).
    Additionally, this package enables stability-based parameter assessment for graph-based clustering pipelines typical in single-cell data analysis.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - lazappi

# Package: ClustAssess
# Type: Package
# Title: Tools for Assessing Clustering
# Version: 0.3.0
# Authors@R: c(person("Arash", "Shahsavari", email="as3006@cam.ac.uk", role = c("aut", "cre")), person("Andi", "Munteanu", email="am3019@cam.ac.uk", role="aut"), person("Irina", "Mohorianu", email="iim22@cam.ac.uk", role="aut"))
# Maintainer: Arash Shahsavari <as3006@cam.ac.uk>
# Description: A set of tools for evaluating clustering robustness using proportion of ambiguously clustered pairs (Senbabaoglu et al. (2014) <doi:10.1038/srep06207>), as well as similarity across methods and method stability using element-centric clustering comparison (Gates et al. (2019) <doi:10.1038/s41598-019-44892-y>). Additionally, this package enables stability-based parameter assessment for graph-based clustering pipelines typical in single-cell data analysis.
# License: MIT + file LICENSE
# Encoding: UTF-8
# Imports: ggplot2, dplyr, fastcluster, rlang, Matrix, igraph, magrittr, Rcpp, methods, stats, foreach, doParallel, irlba, progress, reshape2, stringr, uwot
# RoxygenNote: 7.1.2
# LinkingTo: Rcpp
# Suggests: knitr, rmarkdown, e1071, dbscan, dendextend, Seurat, readr, patchwork
# URL: https://github.com/Core-Bioinformatics/ClustAssess
# BugReports: https://github.com/Core-Bioinformatics/ClustAssess/issues
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2022-01-26 16:10:05 UTC; as3006
# Author: Arash Shahsavari [aut, cre], Andi Munteanu [aut], Irina Mohorianu [aut]
# Repository: CRAN
# Date/Publication: 2022-01-26 16:52:46 UTC
