{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clustassess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ClustAssess_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ClustAssess/ClustAssess_{{ version }}.tar.gz
  sha256: 33d123a18f4212726bca09b68990e14e27520add3e9086cf3f393b68c655fb67

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dt
    - r-gmedian
    - r-matrix >=1.5.0
    - r-rann
    - r-rcpp
    - r-rcppeigen
    - r-seurat
    - r-dplyr
    - r-fastcluster
    - r-foreach
    - r-ggnewscale
    - r-ggplot2
    - r-ggrastr
    - r-ggrepel
    - r-ggtext
    - r-glue
    - r-gprofiler2
    - r-igraph
    - r-jsonlite
    - r-leiden
    - r-matrixstats
    - r-paletteer
    - r-plotly
    - r-progress
    - r-qualpalr
    - r-reshape2
    - r-rlang
    - r-shiny
    - r-shinylp
    - r-shinywidgets
    - r-shinyjs
    - r-stringr
    - r-uwot
    - r-vioplot
  run:
    - r-base
    - r-dt
    - r-gmedian
    - r-matrix >=1.5.0
    - r-rann
    - r-rcpp
    - r-rcppeigen
    - r-seurat
    - r-dplyr
    - r-fastcluster
    - r-foreach
    - r-ggnewscale
    - r-ggplot2
    - r-ggrastr
    - r-ggrepel
    - r-ggtext
    - r-glue
    - r-gprofiler2
    - r-igraph
    - r-jsonlite
    - r-leiden
    - r-matrixstats
    - r-paletteer
    - r-plotly
    - r-progress
    - r-qualpalr
    - r-reshape2
    - r-rlang
    - r-shiny
    - r-shinylp
    - r-shinywidgets
    - r-shinyjs
    - r-stringr
    - r-uwot
    - r-vioplot

test:
  commands:
    - $R -e "library('ClustAssess')"           # [not win]
    - "\"%R%\" -e \"library('ClustAssess')\""  # [win]

about:
  home: https://github.com/Core-Bioinformatics/ClustAssess
  license: MIT
  summary: A set of tools for evaluating clustering robustness using proportion of ambiguously clustered pairs (Senbabaoglu et al. (2014) <doi:10.1038/srep06207>), as well as similarity across methods and method stability using element-centric clustering comparison (Gates et al. (2019) <doi:10.1038/s41598-019-44892-y>).
    Additionally, this package enables stability-based parameter assessment for graph-based clustering pipelines typical in single-cell data analysis.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - lazappi
